# Generated by Django 4.2.4 on 2023-08-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalrate',
            old_name='Vehicle_size',
            new_name='vehicle_size',
        ),
        migrations.RenameField(
            model_name='rentalrate',
            old_name='Vehicle_type',
            new_name='vehicle_type',
        ),
    ]
