# Generated by Django 4.2.4 on 2023-08-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sci', 'scientific'), ('na', 'nature')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
