# Generated by Django 4.2.4 on 2023-08-13 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_book_page_count_alter_book_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review_text',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(10)),
        ),
    ]
