# Generated by Django 4.2.4 on 2023-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('description', models.TextField()),
                ('page_count', models.PositiveIntegerField()),
                ('categories', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
